### ISSUE TITLE
Any way to make an entire program bigger ?

### ISSUE THREAD

**Issue by rncar** [rxi/aq#1]
My eyes are crying with that small font.

By the way, works perfect with Jack using:
```export SDL_AUDIODRIVER=jack```

**Comment by rxi** [comment]
Not currently -- 2x linear scaling could be added without too much hassle. I think there might be a way to start programs with custom scaling on linux. 

Thanks for letting me know about the jack thing, I didn't realise this was something SDL supported.

**Comment by rxi** [comment]
Linear integer scaling can now be set program-wide by calling the function `(ui:set-scale n)` where `n` is the scaling factor.

**Comment by rncar** [comment]
Thanks, works like a charm.
Would be great to use a non integer scaling factor in the future.
